apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31500
  type: NodePort
  selector:
    app: registry
  sessionAffinity: None
