[package]
name = "todo"
version = "0.1.0"
authors = ["zrma <bulbitain@gmail.com>"]

[dependencies]
clap = {version = "^2.32", features = ["yaml"]}
serde_derive = {version = "^1.0.81"}
serde = {version = "^1.0.81"}
serde_json = {version = "^1.0.33"}