apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: ingress-example
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
