apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-public
  namespace: ingress-example
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
    - http:
        paths:
          - path: /web
            backend:
              serviceName: nginx
              servicePort: 80

          - path: /svc/(.*)
            backend:
              serviceName: svc
              servicePort: 80

          - path: /ghost
            backend:
              serviceName: ghost
              servicePort: 80
