apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ingress-example
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
