apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc
  namespace: ingress-example
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: svc
    spec:
      containers:
      - image: mhausenblas/simpleservice:0.5.0
        imagePullPolicy: IfNotPresent
        name: svc
        ports:
        - containerPort: 9876
      dnsPolicy: ClusterFirst
      restartPolicy: Always
