apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: svc
  namespace: ingress-example
  labels:
    app.kubernetes.io/name: ingress-svc
    app.kubernetes.io/part-of: ingress-example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc
  minReplicas: 5
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
